apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  annotations:
    io.katacontainers.restore-from: "/run/vc/vm/snapshots/busybox-kata-multi"
  name: busybox-kata-multi-restored
spec:
  containers:
  - image: docker.io/library/busybox:latest
    imagePullPolicy: Never
    name: busybox-1
    command: ["sh", "-c", "sleep infinity"]
  - image: docker.io/library/busybox:latest
    imagePullPolicy: Never
    name: busybox-2
    command: ["sh", "-c", "sleep infinity"]
  - image: docker.io/library/busybox:latest
    imagePullPolicy: Never
    name: busybox-3
    command: ["sh", "-c", "sleep infinity"]
  runtimeClassName: kata-preview
