apiVersion: v1 
kind: Pod 
metadata: 
  labels: 
    run: busybox 
  annotations:
    io.katacontainers.restore-from: "/run/vc/vm/snapshots/busybox-kata"
  name: busybox-kata-restored
spec: 
  containers: 
  - image: docker.io/library/busybox:latest
    imagePullPolicy: Never
    name: busybox
  runtimeClassName: kata-preview
