apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-kata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-kata
  template:
    metadata:
      labels:
        app: busybox-kata
    spec:
      runtimeClassName: kata-preview
      topologySpreadConstraints:
      - maxSkew: 1
        minDomains: 2
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: busybox-kata
      containers:
      - name: busybox
        image: docker.io/library/busybox:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "sleep infinity"]