apiVersion: v1
kind: Pod
metadata:
  name: busybox-kata
  labels:
    app: busybox-kata-source
spec:
  nodeSelector:
    snapshot-sync.katacontainers.io/source: "true"
  containers:
  - image: docker.io/library/busybox:latest
    imagePullPolicy: Never
    name: busybox
    command: ["sh", "-c", "sleep infinity"]
  runtimeClassName: kata-preview
