apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pyruntime
  name: pyruntime-kata
spec:
  containers:
  - image: docker.io/harshitg/python-runtime:1
    imagePullPolicy: Never
    name: pyruntime
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8888"]
    ports:
    - containerPort: 8888
  runtimeClassName: kata-preview
